# Site specific settings
title: "Sapient Dreams"
name: "Sapient Dreams"
keywords: "Key, words, about, this, website"
baseurl: "/darcli"
url: "http://sapientdreams.com"
description: "Here is the description of Sapient Dreams"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: test
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
